INITIAL_DATA:
  FOLDER: data
  FILE: exportXLS.xls


EXPORT:
  FOLDER: data
  FILE: tableIncomesExpenses.xlsx

  INCOME_TEMPLATE:
    ['Зарплата', 'Дополнительный', 'Лиза', 'Финансовые', 'Награда', 'Другое', 'Командировочные', 'Чужие средства']

  EXPENSE_TEMPLATE:
    [# базовые
     'Еда. Продукты',
     'Еда. Кафе',
     'Повседневное. Проживание',
     'Повседневное. Хоз.товары и т.п.',
     'Повседневное. Живность',
     'Повседневное. Аптека и лечение',
     'Службы. Коммуналка',
     'Службы. Связь',
     'Службы. Лицензии',
     # дорога
     'Авто. Топливо',
     'Авто. Обслуживание',
     'Повседневное. Дорога',
     # вложения в себя
     'Вложения. Крупные покупки',
     'Вложения. Образование',
     'Цезарь. Школа',
     'Вложения. Здоровье',
     'Вложения. Спорт',
     'Вложения. Красота',
     'Вложения. Прочее',
     # прочее
     'Приятное. Развлечения',
     'Лиза. Траты',
     'Лиза. Подарки',
     'Покупки. Одежда',
     'Покупки. Техника',
     'Цезарь. Игрушки',
     'Цезарь. Другое',
     'Приятное. Подарки',
     # годовые суммы
     'Вложения. Финансы',
     'Приятное. Отдых',
     'Покупки. Мебель и ремонт',
     # годовые по прочему
     'Службы. Комиссии',
     'Прочее. Налоги и бюрократия',
     'Деструктив',
     'Прочее. Ошибки',
     'Прочее. Баланс',
     'Прочее. Командировка и закупка',
     'Прочее. Чужие средства']

